spring:
  datasource:
    url: jdbc:mysql://localhost:3306/familyPlan?useSSL=false&useUnicode=true&characterEncoding=UTF8&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.order_by.default_null_ordering: last
server:
  port: 1234